
package generator.common;

import generator.communication.ModuleToCore;

public interface GeneratingLogic
{
	/**
	 * This method is called with given number of examples to be generated by specific thread. This method is also
	 * responsible for taking care of stop of generation when FormalLanguagesGenerator.IS_GENERATING_ACTIVE is set to
	 * false and for providing output to exampleQueue using
	 * FormalLanguagesGenerator.getCoreInstance().getExampleQueue().
	 */
	void executeGeneration();

	void executeGeneration(int numberOfExamples, ModuleToCore moduleToCoreCommunication);
}
